title: Mohit Manna
subtitle: Mohit Manna personal website on Data Engineering Blogs and fun. Blog on data warehouse concepts. Azure AWS and other data related tools
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog.. Hope you love it !!

url: "https://mohit-manna.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.png
author: Mohit Manna
author_bio: Hi, my name is Mohit Manna. I am a Data Engineer who knows about coding and other stuffs 
author_hobbies: Playing outdoor games(Cricket, Football and Volleyball). 
author_email: "mohitmanna49@gmail.com"
author_location: India
author_website_url: "https://mohit-manna.github.io"
typewrite-text: Welcome to my blog. Hope you love it !!

author_work_experiences:
            - company_name: EPAM Systems
              company_logo: epam.png
              company_url: https://epam.com
              designation: Data Engineer
              description: Atlassian CSS, Cost Optimization Project, vNext Migration Project
              visibility: true
            - company_name: To The New
              company_logo: tothenew.png
              company_url: https://tothenew.com
              designation: Data Engineer
              description: Data Accelerator, MAF Project
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: false

author_education_details:
              - college_logo: cdac.png
                college_name: Centre for Development of Advanced Computing, Noida
                college_url: https://cdac.in
                college_degree: MCA
                description: Masters in Computer Applications
                visibility: true
              - college_logo: xaviers.png
                college_name: St. Xavier's College of Management & Tech. Patna
                college_url: http://xaviercollegepatna.org
                college_degree: BCA
                description: Bachelor in Computer Applications
                visibility: true

author_project_details:
              - project_thumbnail: dca.png
                project_title: Data Accelerator
                project_description: A Web Based Generic Data Ingestion, Quality and Validation Platform
                #project_url: 
                visibility: true
              - project_thumbnail: budding.png
                project_title: Budding Bee
                project_description: Simple Website for an Event Management Organisation
                project_url: https://budding-bee.github.io/
                visibility: true
              - project_thumbnail: trendbot.png
                project_title: Trend Bot for Twitter
                project_description: An App which helps you to from Background Task. !
                project_url: https://play.google.com/store/apps/details?id=com.incrementors.trendbot
                visibility: true
              - project_thumbnail: twitcrawl.png
                project_title: TwitCrawl
                project_description: A Basic College Project to showcase NLP and Data Analysis Learning
                project_url: http://twitcrawl.herokuapp.com
                visibility: true

# social links
twitter_username: manna_018
github_username:  mohit-manna
#facebook_username: mohit-manna
linkedin_username: mohit-manna
#behance_username: johndoe
#instagram_username: mohit-manna
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 1461

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://github.us17.list-manage.com/subscribe?u=f208c615642ec0ea10365a78a&id=a3edb14282

# formspree (contact form)
formspree_email: mwpwryao

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
# algolia:
#   application_id: 1XGQDP0A9C
#   index_name: blog # You can replace that with whatever name you want
#   files_to_exclude: []
#   nodes_to_index: 'summary'
#   search_only_api_key: f3c9d1a723cbbb71ec55aabfec1f4657

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
#collections:
# - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
